# Generated by Django 6.0.6 on 2026-06-27 18:36

import accounts.admin
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, default='', max_length=150)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('current_education_status', models.CharField(choices=[('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12'), ('class_12_passed', 'Class 12 Passed'), ('diploma', 'Diploma'), ('ug', 'Undergraduate'), ('graduate', 'Graduate'), ('working', 'Working Professional'), ('unsure', 'Unsure')], db_index=True, default='unsure', max_length=50)),
                ('current_stream', models.CharField(choices=[('pcm', 'Science - PCM'), ('pcb', 'Science - PCB'), ('pcmb', 'Science - PCMB'), ('commerce', 'Commerce'), ('arts', 'Arts / Humanities'), ('vocational', 'Vocational'), ('other', 'Other'), ('unsure', 'Unsure')], db_index=True, default='unsure', max_length=50)),
                ('study_mode_preference', models.CharField(choices=[('regular', 'Regular / On-campus'), ('online', 'Online'), ('distance', 'Distance / ODL'), ('hybrid', 'Hybrid'), ('any', 'Any')], db_index=True, default='any', max_length=50)),
                ('relocation_preference', models.CharField(choices=[('same_city', 'Same city only'), ('same_state', 'Same state'), ('anywhere_india', 'Anywhere in India'), ('online_only', 'Online only'), ('unsure', 'Unsure')], db_index=True, default='unsure', max_length=50)),
                ('preferred_states', models.JSONField(blank=True, default=list)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('max_annual_budget', models.PositiveIntegerField(blank=True, help_text='Maximum yearly budget in INR', null=True)),
                ('needs_scholarship', models.BooleanField(default=False)),
                ('open_to_education_loan', models.BooleanField(default=False)),
                ('interested_subjects', models.JSONField(blank=True, default=list, help_text="Example: ['Computer Science', 'Maths', 'Business']")),
                ('disliked_subjects', models.JSONField(blank=True, default=list, help_text="Example: ['Physics', 'Chemistry']")),
                ('skills', models.JSONField(blank=True, default=list, help_text="Example: ['coding', 'communication', 'design']")),
                ('hobbies', models.JSONField(blank=True, default=list)),
                ('target_careers', models.JSONField(blank=True, default=list, help_text="Example: ['software engineer', 'data analyst', 'doctor']")),
                ('career_goal_text', models.TextField(blank=True, default='', help_text='Free text: what the student wants or is confused about')),
                ('wants_fast_job', models.BooleanField(default=False)),
                ('wants_government_job', models.BooleanField(default=False)),
                ('wants_abroad_option', models.BooleanField(default=False)),
                ('wants_business_or_startup', models.BooleanField(default=False)),
                ('weekly_study_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('maths_comfort', models.PositiveSmallIntegerField(blank=True, help_text='1 weak, 5 strong', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('english_comfort', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('computer_comfort', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_comfort', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('profile_completion_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12'), ('diploma', 'Diploma'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('appearing', 'Appearing'), ('passed', 'Passed'), ('failed', 'Failed'), ('result_awaited', 'Result Awaited')], default='passed', max_length=50)),
                ('board_or_university', models.CharField(blank=True, default='', max_length=255)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('stream', models.CharField(choices=[('pcm', 'Science - PCM'), ('pcb', 'Science - PCB'), ('pcmb', 'Science - PCMB'), ('commerce', 'Commerce'), ('arts', 'Arts / Humanities'), ('vocational', 'Vocational'), ('other', 'Other'), ('unsure', 'Unsure')], db_index=True, default='unsure', max_length=50)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_cgpa', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=4, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Latest/highest relevant qualification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='accounts.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(db_index=True, max_length=150)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('academic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='accounts.candidateacademicrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEntranceExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(db_index=True, help_text='Example: CUET, JEE, NEET, CLAT, NATA', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('category_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exam_scores', to='accounts.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['exam_name'], name='accounts_ca_exam_na_4d0414_idx'), models.Index(fields=['year'], name='accounts_ca_year_286fc9_idx'), models.Index(fields=['percentile'], name='accounts_ca_percent_136901_idx'), models.Index(fields=['rank'], name='accounts_ca_rank_5afb74_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('class_10_marksheet', 'Class 10 Marksheet'), ('class_12_marksheet', 'Class 12 Marksheet'), ('entrance_scorecard', 'Entrance Exam Scorecard'), ('id_proof', 'ID Proof'), ('photo', 'Photo'), ('domicile_certificate', 'Domicile Certificate'), ('category_certificate', 'Category Certificate'), ('income_certificate', 'Income Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('migration_certificate', 'Migration Certificate'), ('other', 'Other')], db_index=True, max_length=100)),
                ('file', models.FileField(upload_to=accounts.admin.candidate_document_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'document_type'], name='accounts_ca_candida_564da5_idx'), models.Index(fields=['is_verified'], name='accounts_ca_is_veri_101d96_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidateacademicrecord',
            index=models.Index(fields=['candidate', 'level'], name='accounts_ca_candida_717fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateacademicrecord',
            index=models.Index(fields=['stream'], name='accounts_ca_stream_38761b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateacademicrecord',
            index=models.Index(fields=['passing_year'], name='accounts_ca_passing_1b52e4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateacademicrecord',
            index=models.Index(fields=['percentage'], name='accounts_ca_percent_e70e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatesubjectscore',
            index=models.Index(fields=['subject_name'], name='accounts_ca_subject_fb058a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatesubjectscore',
            index=models.Index(fields=['percentage'], name='accounts_ca_percent_dd6682_idx'),
        ),
    ]
