# Generated by Django 6.0.6 on 2026-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedocument',
            name='document_type',
            field=models.CharField(choices=[('class_10_marksheet', 'Class 10 Marksheet'), ('class_12_marksheet', 'Class 12 Marksheet'), ('undergraduate_marksheet', 'Undergraduate Marksheet'), ('graduation_marksheet', 'Graduation Marksheet'), ('entrance_scorecard', 'Entrance Exam Scorecard'), ('id_proof', 'ID Proof'), ('photo', 'Photo'), ('domicile_certificate', 'Domicile Certificate'), ('category_certificate', 'Category Certificate'), ('income_certificate', 'Income Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('migration_certificate', 'Migration Certificate'), ('other', 'Other')], db_index=True, max_length=100),
        ),
    ]
