# Generated by Django 6.0.6 on 2026-06-29 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_candidatedocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='current_activity_type',
            field=models.CharField(choices=[('student', 'Student'), ('college_student', 'College Student'), ('employed', 'Employed'), ('self_employed', 'Self Employed'), ('freelancer', 'Freelancer'), ('business_owner', 'Business Owner'), ('content_creator', 'Content Creator / YouTuber'), ('family_business', 'Family Business'), ('unemployed', 'Unemployed / Career Gap'), ('homemaker', 'Homemaker / Career Restart'), ('unsure', 'Unsure')], db_index=True, default='unsure', max_length=50),
        ),
        migrations.CreateModel(
            name='CandidateWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(db_index=True, max_length=50)),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('role_title', models.CharField(blank=True, default='', max_length=150)),
                ('company_or_brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('monthly_income_range', models.CharField(blank=True, default='', max_length=100)),
                ('skills_used', models.JSONField(blank=True, default=list)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('proof_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.candidateprofile')),
            ],
        ),
    ]
