from decimal import Decimal

from django.core.management.base import BaseCommand

from recommendations.models import DemoProgramme


PROGRAMMES = [
    {
        "program_name": "BA LLB",
        "provider": "EazyGrad Demo University",
        "degree_type": "UG",
        "duration": "5 years",
        "fee_range": "₹80,000 - ₹2,50,000/year",
        "min_fee": 80000,
        "max_fee": 250000,
        "mode": "Regular",
        "career_tags": ["law", "government"],
        "background_tags": ["arts", "commerce", "student"],
        "degree_tags": ["law", "government"],
        "duration_years": Decimal("5.0"),
        "description": "legal careers, judiciary, civil services, public policy, and legal advisory work",
    },
    {
        "program_name": "LLB",
        "provider": "National Open Legal Studies Centre",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹60,000 - ₹1,80,000/year",
        "min_fee": 60000,
        "max_fee": 180000,
        "mode": "Regular",
        "career_tags": ["law", "government"],
        "background_tags": ["graduate", "arts", "commerce"],
        "degree_tags": ["law"],
        "duration_years": Decimal("3.0"),
        "description": "students who already have a graduation degree and want to enter legal practice",
    },
    {
        "program_name": "BBA",
        "provider": "EazyGrad School of Business",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹70,000 - ₹1,80,000/year",
        "min_fee": 70000,
        "max_fee": 180000,
        "mode": "Regular",
        "career_tags": ["business", "commerce"],
        "background_tags": ["commerce", "student"],
        "degree_tags": ["business"],
        "duration_years": Decimal("3.0"),
        "description": "management, entrepreneurship, sales, marketing, and business operations roles",
    },
    {
        "program_name": "MBA",
        "provider": "EazyGrad Online Business University",
        "degree_type": "PG",
        "duration": "2 years",
        "fee_range": "₹1,20,000 - ₹4,00,000/year",
        "min_fee": 120000,
        "max_fee": 400000,
        "mode": "Online",
        "career_tags": ["business", "commerce"],
        "background_tags": ["graduate", "working", "commerce"],
        "degree_tags": ["business"],
        "duration_years": Decimal("2.0"),
        "description": "working professionals aiming for management, leadership, and business growth",
    },
    {
        "program_name": "B.Com",
        "provider": "EazyGrad Commerce College",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹25,000 - ₹90,000/year",
        "min_fee": 25000,
        "max_fee": 90000,
        "mode": "Distance",
        "career_tags": ["commerce", "business", "government"],
        "background_tags": ["commerce", "student"],
        "degree_tags": ["commerce"],
        "duration_years": Decimal("3.0"),
        "description": "accounting, banking, finance, government exams, and commerce foundations",
    },
    {
        "program_name": "M.Com",
        "provider": "EazyGrad Distance Learning University",
        "degree_type": "PG",
        "duration": "2 years",
        "fee_range": "₹35,000 - ₹1,00,000/year",
        "min_fee": 35000,
        "max_fee": 100000,
        "mode": "Distance",
        "career_tags": ["commerce", "business", "teaching"],
        "background_tags": ["commerce", "graduate", "working"],
        "degree_tags": ["commerce"],
        "duration_years": Decimal("2.0"),
        "description": "advanced commerce, accounting, teaching eligibility pathways, and finance roles",
    },
    {
        "program_name": "BA Political Science",
        "provider": "EazyGrad Liberal Arts University",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹30,000 - ₹1,10,000/year",
        "min_fee": 30000,
        "max_fee": 110000,
        "mode": "Distance",
        "career_tags": ["government", "law"],
        "background_tags": ["arts", "student"],
        "degree_tags": ["government"],
        "duration_years": Decimal("3.0"),
        "description": "civil services, public policy, law preparation, and governance-focused careers",
    },
    {
        "program_name": "BA Public Administration",
        "provider": "People's Distance University",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹28,000 - ₹95,000/year",
        "min_fee": 28000,
        "max_fee": 95000,
        "mode": "Distance",
        "career_tags": ["government"],
        "background_tags": ["arts", "student", "working"],
        "degree_tags": ["government"],
        "duration_years": Decimal("3.0"),
        "description": "government services, administration, policy, and public-sector preparation",
    },
    {
        "program_name": "BCA",
        "provider": "EazyGrad Institute of Technology",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹55,000 - ₹1,50,000/year",
        "min_fee": 55000,
        "max_fee": 150000,
        "mode": "Online",
        "career_tags": ["technology", "data"],
        "background_tags": ["science", "commerce", "student"],
        "degree_tags": ["technology"],
        "duration_years": Decimal("3.0"),
        "description": "software development, IT support, web applications, and technical career paths",
    },
    {
        "program_name": "MCA",
        "provider": "EazyGrad Online Tech University",
        "degree_type": "PG",
        "duration": "2 years",
        "fee_range": "₹80,000 - ₹2,20,000/year",
        "min_fee": 80000,
        "max_fee": 220000,
        "mode": "Online",
        "career_tags": ["technology", "data"],
        "background_tags": ["graduate", "working", "science"],
        "degree_tags": ["technology"],
        "duration_years": Decimal("2.0"),
        "description": "advanced software, application development, systems, and IT leadership roles",
    },
    {
        "program_name": "B.Sc Data Science",
        "provider": "EazyGrad Analytics University",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹75,000 - ₹2,00,000/year",
        "min_fee": 75000,
        "max_fee": 200000,
        "mode": "Regular",
        "career_tags": ["data", "technology", "science"],
        "background_tags": ["science", "commerce", "student"],
        "degree_tags": ["data"],
        "duration_years": Decimal("3.0"),
        "description": "data analysis, statistics, machine learning foundations, and analytics careers",
    },
    {
        "program_name": "PG Diploma Data Analytics",
        "provider": "EazyGrad Professional Academy",
        "degree_type": "Diploma",
        "duration": "1 year",
        "fee_range": "₹45,000 - ₹1,40,000/year",
        "min_fee": 45000,
        "max_fee": 140000,
        "mode": "Online",
        "career_tags": ["data", "technology"],
        "background_tags": ["graduate", "working", "commerce", "science"],
        "degree_tags": ["data"],
        "duration_years": Decimal("1.0"),
        "description": "job-focused analytics, dashboards, SQL, spreadsheets, and business data roles",
    },
    {
        "program_name": "PG Diploma Digital Marketing",
        "provider": "EazyGrad Skills University",
        "degree_type": "Diploma",
        "duration": "1 year",
        "fee_range": "₹35,000 - ₹1,20,000/year",
        "min_fee": 35000,
        "max_fee": 120000,
        "mode": "Online",
        "career_tags": ["business", "media"],
        "background_tags": ["commerce", "arts", "working"],
        "degree_tags": ["business", "media"],
        "duration_years": Decimal("1.0"),
        "description": "marketing, social media, performance campaigns, and creator-led business growth",
    },
    {
        "program_name": "B.Ed",
        "provider": "EazyGrad College of Education",
        "degree_type": "UG",
        "duration": "2 years",
        "fee_range": "₹45,000 - ₹1,30,000/year",
        "min_fee": 45000,
        "max_fee": 130000,
        "mode": "Regular",
        "career_tags": ["teaching"],
        "background_tags": ["graduate", "working", "arts", "science", "commerce"],
        "degree_tags": ["teaching"],
        "duration_years": Decimal("2.0"),
        "description": "school teaching, education roles, and formal teacher qualification pathways",
    },
    {
        "program_name": "BA Journalism",
        "provider": "EazyGrad Media College",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹50,000 - ₹1,60,000/year",
        "min_fee": 50000,
        "max_fee": 160000,
        "mode": "Regular",
        "career_tags": ["media"],
        "background_tags": ["arts", "student"],
        "degree_tags": ["media"],
        "duration_years": Decimal("3.0"),
        "description": "journalism, reporting, content production, media writing, and communication careers",
    },
    {
        "program_name": "B.Sc Psychology",
        "provider": "EazyGrad Social Sciences University",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹60,000 - ₹1,80,000/year",
        "min_fee": 60000,
        "max_fee": 180000,
        "mode": "Regular",
        "career_tags": ["psychology", "teaching"],
        "background_tags": ["science", "arts", "student"],
        "degree_tags": ["psychology"],
        "duration_years": Decimal("3.0"),
        "description": "psychology foundations, counselling pathways, human behaviour, and research careers",
    },
    {
        "program_name": "B.Des",
        "provider": "EazyGrad Design Institute",
        "degree_type": "UG",
        "duration": "4 years",
        "fee_range": "₹1,20,000 - ₹3,50,000/year",
        "min_fee": 120000,
        "max_fee": 350000,
        "mode": "Regular",
        "career_tags": ["design"],
        "background_tags": ["arts", "science", "commerce", "student"],
        "degree_tags": ["design"],
        "duration_years": Decimal("4.0"),
        "description": "product design, visual communication, UX, creative problem solving, and portfolio-led careers",
    },
    {
        "program_name": "B.Sc Mathematics",
        "provider": "EazyGrad Science University",
        "degree_type": "UG",
        "duration": "3 years",
        "fee_range": "₹40,000 - ₹1,20,000/year",
        "min_fee": 40000,
        "max_fee": 120000,
        "mode": "Regular",
        "career_tags": ["science", "data", "government"],
        "background_tags": ["science", "student"],
        "degree_tags": ["science", "data"],
        "duration_years": Decimal("3.0"),
        "description": "quantitative careers, analytics, teaching, research, and exam preparation",
    },
    {
        "program_name": "MA Political Science",
        "provider": "EazyGrad Distance Learning University",
        "degree_type": "PG",
        "duration": "2 years",
        "fee_range": "₹35,000 - ₹1,10,000/year",
        "min_fee": 35000,
        "max_fee": 110000,
        "mode": "Distance",
        "career_tags": ["government", "law"],
        "background_tags": ["graduate", "arts", "working"],
        "degree_tags": ["government"],
        "duration_years": Decimal("2.0"),
        "description": "civil services, public policy, research, governance, and teaching pathways",
    },
    {
        "program_name": "Diploma in Business Management",
        "provider": "EazyGrad Professional Academy",
        "degree_type": "Diploma",
        "duration": "1 year",
        "fee_range": "₹30,000 - ₹95,000/year",
        "min_fee": 30000,
        "max_fee": 95000,
        "mode": "Online",
        "career_tags": ["business", "commerce"],
        "background_tags": ["commerce", "working", "student"],
        "degree_tags": ["business"],
        "duration_years": Decimal("1.0"),
        "description": "practical business basics, team management, operations, and career switching",
    },
]


class Command(BaseCommand):
    help = "Seed demo programmes for the public AI course search prototype."

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for programme in PROGRAMMES:
            _, was_created = DemoProgramme.objects.update_or_create(
                program_name=programme["program_name"],
                defaults=programme,
            )

            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded demo programmes. Created: {created}. Updated: {updated}."
            )
        )
