# Generated by Django 6.0.6 on 2026-06-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, default='', max_length=1000)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('subjects', models.TextField()),
                ('seats', models.CharField(blank=True, default='', max_length=50)),
                ('fees', models.CharField(blank=True, default='', max_length=100)),
                ('syllabus', models.TextField()),
                ('ideal_student', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='vendors.vendorinstitute')),
            ],
        ),
    ]
