# Generated by Django 6.0.6 on 2026-06-30 08:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcourse',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vendorcourse',
            index=models.Index(fields=['title'], name='vendors_ven_title_1f0f82_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcourse',
            index=models.Index(fields=['level'], name='vendors_ven_level_a053bd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcourse',
            index=models.Index(fields=['mode'], name='vendors_ven_mode_5b446f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcourse',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vendors_ven_search__b62cac_gin'),
        ),
    ]
