# Generated by Django 6.0.6 on 2026-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=600)),
                ('university_type', models.CharField(choices=[('central', 'Central University'), ('state', 'State University'), ('deemed', 'Deemed to be University'), ('private', 'State Private University'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('ugc_status', models.CharField(blank=True, default='', help_text='Example: 2(f), 12(B), Section-III etc.', max_length=100)),
                ('website_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source', models.CharField(choices=[('ugc', 'University Grants Commission')], db_index=True, default='ugc', max_length=50)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_sr_no', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='institution_name_fc9596_idx'), models.Index(fields=['state'], name='institution_state_610614_idx'), models.Index(fields=['university_type'], name='institution_univers_383de1_idx'), models.Index(fields=['source'], name='institution_source_9f1d65_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'state', 'university_type'), name='unique_university_name_state_type')],
            },
        ),
    ]
