# Generated by Django 6.0.6 on 2026-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_fake',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('central', 'Central University'), ('state', 'State University'), ('deemed', 'Deemed to be University'), ('private', 'State Private University'), ('fake', 'Fake University'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_fake'], name='institution_is_fake_745cd7_idx'),
        ),
    ]
