# Generated by Django 6.0.6 on 2026-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_university_is_fake_alter_university_university_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='ugc_status',
            field=models.CharField(blank=True, default='', help_text='Example: 2(f), 12(B), Section-III etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
