# Generated by Django 6.0.6 on 2026-06-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_university_ugc_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCDEBProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=20)),
                ('session', models.CharField(blank=True, default='', max_length=100)),
                ('mode', models.CharField(blank=True, db_index=True, default='', help_text='Example: Online (Entitled), ODL (Recognised)', max_length=150)),
                ('hei_name', models.CharField(db_index=True, help_text='Higher Education Institution name from UGC-DEB', max_length=500)),
                ('hei_type', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('program_name', models.CharField(db_index=True, max_length=500)),
                ('level', models.CharField(blank=True, db_index=True, default='', help_text='UG / PG', max_length=20)),
                ('source', models.CharField(db_index=True, default='ugc_deb', max_length=50)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, help_text='Matched University from UGC master data, if found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deb_programmes', to='institutions.university')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='institution_year_73ed4e_idx'), models.Index(fields=['mode'], name='institution_mode_7dae7b_idx'), models.Index(fields=['state'], name='institution_state_70001c_idx'), models.Index(fields=['level'], name='institution_level_99d838_idx'), models.Index(fields=['hei_name'], name='institution_hei_nam_0c9cb6_idx'), models.Index(fields=['program_name'], name='institution_program_0bcb44_idx'), models.Index(fields=['university'], name='institution_univers_e0204e_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'mode', 'hei_name', 'state', 'program_name', 'level'), name='unique_ugc_deb_programme')],
            },
        ),
    ]
