# Generated by Django 6.0.6 on 2026-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_ugcdebprogramme'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='aishe_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='aishe_website',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='university',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Example: Rural / Urban', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='year_of_establishment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
