# Generated by Django 6.0.6 on 2026-06-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_university_aishe_code_university_aishe_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIRFRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, default=2025)),
                ('category', models.CharField(choices=[('overall', 'Overall'), ('university', 'University'), ('college', 'College'), ('engineering', 'Engineering'), ('management', 'Management'), ('medical', 'Medical'), ('law', 'Law'), ('pharmacy', 'Pharmacy')], db_index=True, max_length=50)),
                ('institute_id', models.CharField(db_index=True, help_text='Example: IR-O-U-0456', max_length=100)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('rank', models.CharField(blank=True, db_index=True, default='', help_text='Can be normal rank like 1 or rank-band like 101-150', max_length=50)),
                ('tlr_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rpc_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('go_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perception_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=1000)),
                ('graph_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, help_text='Matched University from UGC/AISHE master data, if found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nirf_rankings', to='institutions.university')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='institution_year_78a382_idx'), models.Index(fields=['category'], name='institution_categor_2fbd08_idx'), models.Index(fields=['institute_id'], name='institution_institu_1b8ac4_idx'), models.Index(fields=['name'], name='institution_name_7d9829_idx'), models.Index(fields=['state'], name='institution_state_977b2d_idx'), models.Index(fields=['city'], name='institution_city_587ee0_idx'), models.Index(fields=['score'], name='institution_score_7ced75_idx'), models.Index(fields=['rank'], name='institution_rank_2cfe38_idx'), models.Index(fields=['university'], name='institution_univers_111bee_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'category', 'institute_id'), name='unique_nirf_year_category_institute')],
            },
        ),
    ]
