# Generated by Django 6.0.6 on 2026-06-27 17:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_nirfranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='source',
            field=models.CharField(choices=[('ugc', 'University Grants Commission'), ('aishe', 'All India Survey on Higher Education'), ('ugc_deb', 'UGC Distance Education Bureau'), ('nirf', 'National Institutional Ranking Framework')], db_index=True, default='ugc', max_length=50),
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('university', 'University'), ('ugc_deb_programme', 'UGC-DEB Programme'), ('nirf_ranking', 'NIRF Ranking')], db_index=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=700)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1000)),
                ('body', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='Example: nirf overall, ugc university, ugc-deb online programme', max_length=100)),
                ('level', models.CharField(blank=True, db_index=True, default='', help_text='Example: UG / PG', max_length=50)),
                ('mode', models.CharField(blank=True, db_index=True, default='', help_text='Example: Online / ODL / Regular', max_length=150)),
                ('year', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('rank', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nirf_ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='institutions.nirfranking')),
                ('ugc_deb_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='institutions.ugcdebprogramme')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='institutions.university')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_document_vector_gin_idx'), models.Index(fields=['entity_type', 'source_id'], name='institution_entity__b4beed_idx'), models.Index(fields=['state'], name='institution_state_785929_idx'), models.Index(fields=['city'], name='institution_city_8585d5_idx'), models.Index(fields=['category'], name='institution_categor_d61bbc_idx'), models.Index(fields=['mode'], name='institution_mode_d0cc0c_idx'), models.Index(fields=['level'], name='institution_level_843cfd_idx'), models.Index(fields=['year'], name='institution_year_ec341f_idx'), models.Index(fields=['rank'], name='institution_rank_9101ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'source_id'), name='unique_search_document_entity_source')],
            },
        ),
    ]
