# Generated by Django 6.0.6 on 2026-06-29 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_candidatedocument_document_type'),
        ('institutions', '0007_alter_university_source_searchdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_signature', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('ai_explanation', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='accounts.candidateprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankedCourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('final_score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('match_percentage', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('recommendation_type', models.CharField(choices=[('strong_recommendation', 'Strong Recommendation'), ('good_option', 'Good Option'), ('backup_option', 'Backup Option'), ('future_path', 'Future Path'), ('not_recommended', 'Not Recommended')], db_index=True, max_length=40)),
                ('filter_status', models.CharField(db_index=True, max_length=30)),
                ('filter_reasons', models.JSONField(blank=True, default=list)),
                ('filter_penalties', models.JSONField(blank=True, default=list)),
                ('eligibility', models.JSONField(blank=True, default=dict)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('negative_factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_recommendations', to='accounts.candidateprofile')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_recommendations', to='institutions.ugcdebprogramme')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationrun')),
            ],
            options={
                'ordering': ['rank', '-final_score'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['candidate', 'profile_signature'], name='recommendat_candida_d4c1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['requested_by', 'status'], name='recommendat_request_9b26b7_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['created_at'], name='recommendat_created_015f15_idx'),
        ),
        migrations.AddIndex(
            model_name='rankedcourserecommendation',
            index=models.Index(fields=['candidate', 'recommendation_type'], name='recommendat_candida_8e60f2_idx'),
        ),
        migrations.AddIndex(
            model_name='rankedcourserecommendation',
            index=models.Index(fields=['run', 'rank'], name='recommendat_run_id_c8da1e_idx'),
        ),
        migrations.AddIndex(
            model_name='rankedcourserecommendation',
            index=models.Index(fields=['programme', 'final_score'], name='recommendat_program_242744_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankedcourserecommendation',
            constraint=models.UniqueConstraint(fields=('run', 'programme'), name='unique_recommendation_run_programme'),
        ),
    ]
