# Generated by Django 6.0.6 on 2026-06-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedcourserecommendation',
            name='match_percentage',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
